### ISSUE TITLE
Loom State Recording and Reporting

### ISSUE THREAD

**Issue by Cogswatch** [OPEnSLab-OSU/Loom#13]
Add SD Logging of Error handling or edge case events, consider implementing watchdog longjump for failure recovery.

**Comment by prototypicalpro** [comment]
Loom doesn't currently keep a ledger of previous events (sensor creation, errors, etc.) and as a result it can be difficult to troubleshoot what is going wrong. Loom should be able to store a history of events on another medium other than the micro controller, such that a developer can access these logs after a failure.

Events should include:
 * Sensor creation/destruction
 * Timeouts
 * Errors
 * Metadata/information
 * Hardware status (free memory)
 * An accurate timestamp, or at least a useful relative one.

**Comment by Cogswatch** [comment]
This can be solved with FeatherFault, consider implementing it into core Loom to resolve this issue.

**Comment by udellc** [comment]
FeatherFault is integrated in Loom3, addresses many of these features
