### ISSUE TITLE
Template Issues

### ISSUE THREAD

**Issue by prototypicalpro** [OPEnSLab-OSU/Loom#14]
Loom doesn't specify what should be contained in an issue other than it should contain a lot of information. An issue template for each type of issue (bug, enhancement, feature request, etc.) with appropriate heading would be useful to people writing issues. An example of what I'm thinking of can be found here: https://github.com/stevemao/github-issue-templates/blob/master/bugs-only/ISSUE_TEMPLATE.md

**Comment by Cogswatch** [comment]
Issue templates have been added for the most common issue tags.
