### ISSUE TITLE
SD not initializing after waking up from sleep

### ISSUE THREAD

**Issue by BGoto808** [OPEnSLab-OSU/Loom#143]
**Describe the bug**
After the Feather goes to sleep, the Feather wakes up and takes data, but none of it is recorded into the SD. 

**Hardware in Use**
From BEE222:
* Feather M0
* STEMMA sensor
* SD module

**To Reproduce**
1. Create a sketch from basic.ino and include the STEMMA, SD, Interrupt and Sleep Manager in the config
2. Make sure in loop, the Feather takes data, logs to SD, and goes to sleep

**Expected behavior**
The Feather should wake up as usual and take data and successfully log to SD

**Code**
None

**Config**
None

**Comment by lucasballr** [comment]
I was able to improve the consistency of the logging by calling Loom.power_up() at the beginning of the loop. This is being done in the hypnos_SD_Sleep.ino example, but only when the board is awoken by the interrupt pin.
