### ISSUE TITLE
Loom Diagnostic Routine

### ISSUE THREAD

**Issue by prototypicalpro** [OPEnSLab-OSU/Loom#15]
Loom does not currently have a "self-test" routine, which makes the data reported only indication of functionality. A self-test routine would allow each sensor/internet platform to report much more verbose information about its state and functionality, making diagnostics faster. My idea for a self-test routine would:
* Verify that the internet is accessible
* Verify that all network devices are responsive
* Verify that each sensor is configured correctly (checking for a dead sensor) and that the reported data is within reason (checking for a broken analog connection)
* Verify that the device is configured correctly/all devices are present.

**Comment by udellc** [comment]
Unresolved: Archived to later consideration
