### ISSUE TITLE
Arduino IDE Library Unsearchable

### ISSUE THREAD

**Issue by DexterCarpenter** [OPEnSLab-OSU/Loom#178]
**Describe the bug**
In trying to find the Loom library in the Arduino IDE library manager, no results are found for search terms 'Loom' or 'SAMD'.

**Hardware in Use**
Arduino IDE ver. 1.8.19 (old)
Windows 10 Microsoft Surface
Windows 10 PC
Additional Windows Laptop (Cameron W)

**To Reproduce**
1. Open Arduino IDE, Loom does not need to be pre-installed. This issue arises whether loom is pre-installed or not.
2. Go to File>Preferences>Additional Board Manager URLs and ensure that `https://adafruit.github.io/arduino-board-index/package_adafruit_index.json,https://github.com/OPEnSLab-OSU/Loom_Auxiliary/raw/master/package_loom_index.json` is included.
3. Navigate to Sketch>Include Library>Manage Libraries...
4. Search 'Loom' on Type: All, Topic: All
5. No results are found.

**Expected behavior**
The loom library does not show up, no versions shown whatsoever.

**Code**
Occurs regardless of code being uploaded. This occurs on a blank sketch.

**Config**
Occurs regardless of code being uploaded. This occurs with no config file.

**Additional context**
I came across this issue 2/14/22 around 1:00PM with Cameron W while trying to check to see if my loom version was up to date, and found that I couldn't find the loom library in the library manager.

**Comment by WL-Richards** [comment]
Yes, this is expected. The library gets installed alongside the board profile, not standalone

You can find the version by going Tools > Board > Board Manager and then searching Loom

Loom SAMD Boards should show up then.
