### ISSUE TITLE
Investigate why you can't go into deep sleep with Arduino (disconnect WiFi) when using WiFi MQTT Connectivity.

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom#186]
Not conclusive; figure out? Will this work with the "Exploded" approach?

**Comment by WL-Richards** [comment]
Put in maxLowPower instead of powering it off

**Comment by WL-Richards** [comment]
https://learn.adafruit.com/adafruit-feather-m0-wifi-atwinc1500/power-management
