### ISSUE TITLE
Ultrasonic Flowmeter TUF-2000M Implementation Request

### ISSUE THREAD

**Issue by osuwalkera6** [OPEnSLab-OSU/Loom#19]
I would like to ask for the TUF-2000M to be implemented into Loom. It uses a 4mA-20mA analog signal to transmit information about the flow through a section of pipe. I will leave the documentation for the device below and I will get back to you on whether the signal behaves linearly with the flow.

Technical Manual: https://images-na.ssl-images-amazon.com/images/I/91CvZHsNYBL.pdf

**Comment by udellc** [comment]
This is being conducted on the ADS1115 ADC, which *is* Loom integrated.
