### ISSUE TITLE
Adafruit I2C Soil Moisture Sensor Integration Request

### ISSUE THREAD

**Issue by maxchu765** [OPEnSLab-OSU/Loom#21]
I would like these new I2C soil moisture sensors to be integrated. 

https://www.adafruit.com/product/4026

**Comment by maxchu765** [comment]
I tested the sensor with Adafruit's example code and it works, There is a library for the sensor. Here is the link with the example code.
https://learn.adafruit.com/adafruit-stemma-soil-sensor-i2c-capacitive-moisture-sensor/arduino-test

**Comment by prototypicalpro** [comment]
Additionally add support to for the I2C multiplexer plugging.

**Comment by eliwinkelman** [comment]
@maxchu765 Is there one of these sensors I can test the integration with?

**Comment by maxchu765** [comment]
@eliwinkelman There's a bunch in the RFID moisture project cabinet that you can grab.

**Comment by eliwinkelman** [comment]
This is now in the development branch of Loom
