### ISSUE TITLE
Transition auto-documentation into a more readable standard

### ISSUE THREAD

**Issue by Cogswatch** [OPEnSLab-OSU/Loom#22]
At this point in time, the documentation, while being incredibly verbose and effective, simply isn't viable and/or friendly enough to be useful for most users. Modifying the wiki for more obvious access as well as selecting a more appealing documentation form factor should be considered.

**Possible Themes/Schemes**
* [Natural Docs](https://www.naturaldocs.org/)
* [Doxygen C++ theme](https://mcss.mosra.cz/documentation/doxygen/)
* [Custom Modification](http://www.doxygen.nl/manual/customize.html)
* [Bootstrap](https://github.com/Velron/doxygen-bootstrapped)
* [Moxygen](https://sourcey.com/articles/generating-beautiful-cpp-markdown-documentation-with-moxygen)

**Comment by akerr501** [comment]
Loom now supports a more user-friendly auto-documentation in version [2.4.0](https://github.com/OPEnSLab-OSU/Loom/releases/tag/2.4.0). This also uses XML generation which solves issue #30. The newly supported documentation can be found [here](https://openslab-osu.github.io/Loom/doxygenV2/html/index.html) and Loom still supports its verbose original Doxygen documentation which can be found [here](https://openslab-osu.github.io/Loom/html/index.html)
