### ISSUE TITLE
i2C MUX + Hypnos needs powerup re-init

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Loom#25]
**Describe the bug**
Using the Hypnos board to power the i2c MUX down and back up in between sleep cycles, MUX does not retain initialization. This should be handled as part of a larger issue with powering down/up devices in general.

**Hardware in Use**
Feather M0
Hypnos
i2c MUX powered on the switched rails from Hypnos

**To Reproduce**
Connect hardware together. Put Mux to power down via hypnos using Loom sleep functions

**Expected behavior**
Mux should work the same after power down as before

**Code**
Get from Max Chu

**Config**
Get from Max Chu

**Additional context**

**Comment by prototypicalpro** [comment]
Fixed with https://github.com/OPEnSLab-OSU/Loom/commit/e42d600c2249a2a952dc53896cce4fc1d25d615b.
