### ISSUE TITLE
ADS1115

### ISSUE THREAD

**Issue by osuwalkera6** [OPEnSLab-OSU/Loom#27]
**Item's use**
Analog to Digital Converter; uses 16bit I2C; very accurate with 4 Analog inputs & various gain settings.

**Product Page**
https://www.adafruit.com/product/1085

[ADS1115 example.docx](https://github.com/OPEnSLab-OSU/Loom/files/3745798/ADS1115.example.docx)

**Comment by SRGDamia1** [comment]
Use the Soligen fork of the ADS library, not the Adafruit main branch.

**Comment by SRGDamia1** [comment]
That's the one.
