### ISSUE TITLE
Enable Doxygen XML Generation

### ISSUE THREAD

**Issue by Cogswatch** [OPEnSLab-OSU/Loom#30]
**Is your feature request related to a problem? Please describe.**
Doxygen offers a syntax-tree-like system by toggling ```GENERATE_XML = YES``` which provides a perfect entry point into parsing the Loom class structure. Why go through the effort of regexping the configurator when you can take advantage of whats already in front of you?

**Describe the solution you'd like**
Pivot configurator from manual string manipulation towards doxygen xml filtering using the npm package xml2json, which will provide an easy way to extract constructor data. If doxygen provides support for custom tagging, or parameter metadata, than we can piggyback straight off that when it comes to converting the JSON as it is provided into an effective schema with far less overhead.

**Describe alternatives you've considered**
Learning Bison and figuring out how to build that into a Travis workflow, but the overhead on that would be immense and costly in terms of time and resources.

**Comment by akerr501** [comment]
Loom now supports XML generation for its auto-documentation in version [2.4.0](https://github.com/OPEnSLab-OSU/Loom/releases/tag/2.4.0). This also provides a more user-friendly documentation solving issue #22. The newly supported documentation can be found [here](https://openslab-osu.github.io/Loom/doxygenV2/html/index.html) and Loom still supports its verbose original Doxygen documentation which can be found [here](https://openslab-osu.github.io/Loom/html/index.html)
