### ISSUE TITLE
Using more than one MS5803 pressure sensor with the mux returns the wrong temperture

### ISSUE THREAD

**Issue by maxchu765** [OPEnSLab-OSU/Loom#34]
**Describe the bug**
When using more than one MS80302 pressure sensor, one of the sensors reports temperature about 10 degrees Celsius low. Pressure readings are accurate for both sensors. Only the temperature for one sensor is wrong.

**Hardware in Use**
Feather M0 LoRa
I2C multiplexer
2 MS580302 Pressure sensors

**Code**
LOOM multiplexer example

**Additional context**
Both pressure  sensors by themselves report the correct temperature and pressure

**Comment by prototypicalpro** [comment]
Will be fixed with https://github.com/OPEnSLab-OSU/Loom/issues/25

**Comment by maxchu765** [comment]
Currently fixed by re-initializing the sensor right before reading the data.
