### ISSUE TITLE
MMA8451 Accelerometer Interrupt Functionality.

### ISSUE THREAD

**Issue by maxchu765** [OPEnSLab-OSU/Loom#35]
**Item's use**
The MMA8451's interrupt feature would be used to send an interrupt signal to the feather and wake it up when a large acceleration is detected.

**Product Page**
https://www.adafruit.com/product/2019

**Existing Implementation**
The adafruit library does not support the interrupt feature. The feature has been used on the Slide Sentinel and SitkaNet V1 projects.

**Comment by prototypicalpro** [comment]
Support for this feature has been added through Loom's [InterruptManager](https://github.com/OPEnSLab-OSU/Loom/wiki/Features#interrupt-manager).
