### ISSUE TITLE
SD card logging does not have dates. 

### ISSUE THREAD

**Issue by maxchu765** [OPEnSLab-OSU/Loom#43]
**Describe the bug**
When logging to microSD card, there are no dates in the timestamp. The date column has pound symbols instead. 
![image](https://user-images.githubusercontent.com/12554159/68440608-8199bf80-0180-11ea-9d42-b5565cb86ea9.png)

**Hardware in Use**
Feather M0 Proto
Hypnos 

**Expected behavior**
Correct date should be logged to SD.

**Code**
Hypnos_SD example

**Config**
Example config

**Comment by SRGDamia1** [comment]
Did you try expanding the width of the column in excel?

**Comment by maxchu765** [comment]
That fixed it.
