### ISSUE TITLE
Installing Loom 2 

### ISSUE THREAD

**Issue by dnspring** [OPEnSLab-OSU/Loom#47]
**Describe the bug**
In file included from C:\Users\Alex\Documents\Arduino\libraries\Loom-master\src/Loom_Module_Factory.h:69:0,

                 from C:\Users\Alex\Documents\Arduino\libraries\Loom-master\src/Loom_Manager.h:17,

                 from C:\Users\Alex\Documents\Arduino\libraries\Loom-master\src/Loom.h:32,

                 from C:\Users\Alex\Documents\Arduino\libraries\Loom-master\examples\Basic\Basic.ino:20:

C:\Users\Alex\Documents\Arduino\libraries\Loom-master\src/Sensors/I2C/Loom_STEMMA.h:4:10: fatal error: Adafruit_seesaw.h: No such file or directory

 #include "Adafruit_seesaw.h"

**Hardware in Use**
Feather M0 board 

**To Reproduce**

**Expected behavior**
Im just running the test to make sure my libraries are right

**Code**
In file included from C:\Users\Alex\Documents\Arduino\libraries\Loom-master\src/Loom_Module_Factory.h:69:0,

                 from C:\Users\Alex\Documents\Arduino\libraries\Loom-master\src/Loom_Manager.h:17,

                 from C:\Users\Alex\Documents\Arduino\libraries\Loom-master\src/Loom.h:32,

                 from C:\Users\Alex\Documents\Arduino\libraries\Loom-master\examples\Basic\Basic.ino:20:

C:\Users\Alex\Documents\Arduino\libraries\Loom-master\src/Sensors/I2C/Loom_STEMMA.h:4:10: fatal error: Adafruit_seesaw.h: No such file or directory

 #include "Adafruit_seesaw.h"

**Config**
In the Arduino IDE while editing the config.json, goto 'Edit' -> 'Copy for HTML' and paste the output of that here

**Additional context**

**Comment by prototypicalpro** [comment]
Hello! It looks like you've found an issue with our installation instructions. I've created an [issue to address this problem](https://github.com/OPEnSLab-OSU/Loom/issues/48), and will be working on fixing it in the next week. 

In the meantime, you can fix your installation of Loom using the Arduino IDE:
 1. In the Arduino IDE, navigate to `Tools -> Manage Libraries... `
 2. Once the library manager finishes loading, enter `seesaw` as the search term and press enter to search.
 3. In the "Adafruit seesaw Library" box, select the highest version, and click `Install`. Once this process completes, Loom should have everything it needs to function properly.

I'm going to close this issue, please feel free to open it again if you continue to run into issues.
