### ISSUE TITLE
Board Manager Profile

### ISSUE THREAD

**Issue by Cogswatch** [OPEnSLab-OSU/Loom#51]
**Is your feature request related to a problem? Please describe.**
Switch from serving all libraries and dependencies as an external installer or manual process into 'board specific' LoomSamd21 platform libraries which will allow full setup in one action.

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
Building an instal .sh

**Additional context**
https://github.com/sensebox/senseBoxMCU-core

**Comment by akerr501** [comment]
Loom now supports a Board Profile in version [2.4.0](https://github.com/OPEnSLab-OSU/Loom/releases/tag/2.4.0) and quick start install instructions can be found [here](https://github.com/OPEnSLab-OSU/Loom/wiki/Arduino-and-Loom-Quick-Setup) and manual install instructions can be found [here](https://github.com/OPEnSLab-OSU/Loom/wiki/Arduino-and-Loom-Manual-Setup)
