### ISSUE TITLE
Smart Rock Sleep Manager

### ISSUE THREAD

**Issue by veacha** [OPEnSLab-OSU/Loom#61]
Can someone from the Loom team take a look at my Loom code for [Smart Rock Testing](https://github.com/OPEnSLab-OSU/SmartRock/tree/master/Testing/SmartRockFieldTesting)? 
Sleep manager is not working anymore- it used to.
Need this as soon as you can - thank you.

**Comment by prototypicalpro** [comment]
Issue ended up being a dead battery in the RTC featherwing, which caused the feather to hang when attempting to read it.
