### ISSUE TITLE
Replace analogRead with a correct implementation

### ISSUE THREAD

**Issue by prototypicalpro** [OPEnSLab-OSU/Loom#9]
The Arduino implementation of `analogRead()` is incorrect: https://www.omzlo.com/articles/your-arduino-samd21-adc-is-wrong-did-you-notice . This problem was tested and confirmed to be appearing with the Feather M0s.

A possible solution is to replace all instanced of the `analogRead` function with an alternative presented in the blog post above:
```C++
uint32_t adcRead(void)
{
  REG_ADC_CTRLA = 2;
  REG_ADC_INPUTCTRL = 0x0F001800;
  REG_ADC_SWTRIG = 2;
  while (!(REG_ADC_INTFLAG & 1));
  return REG_ADC_RESULT;
}
```
This function may need to be modified to support different pins other that A0.

**Comment by akerr501** [comment]
This has been fixed a while ago in the Arduino Core samd21. This can be seen [here](https://github.com/arduino/ArduinoCore-samd/pull/447) and [here](https://github.com/tuniii/platformio-pkg-framework-arduinosam/commit/da3584995a642a396fa3926b70e88033198a512e). As long as you have the board profile of the Arduino SAMD 21 with version 1.8.4 or higher, the readings will be accurate. To install the latest version, you can go to Tools->Boards->Board Manager and search SAMD and update to the latest version for Arduino SAMD Boards
